LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY EDGEDTCTR IS
    GENERIC (
        REG_LENGTH : POSITIVE := 1
    );
    PORT (
        CLK, RST_N : IN STD_ULOGIC;
        SYNC_IN : IN STD_ULOGIC;
        EDGE : OUT STD_ULOGIC
    );
END EDGEDTCTR;

ARCHITECTURE BEHAVIORAL OF EDGEDTCTR IS
    SIGNAL sreg : STD_ULOGIC_VECTOR(REG_LENGTH DOWNTO 0);
BEGIN
    PROCESS (CLK, RST_N)
    BEGIN
        IF RST_N = '0' THEN
            sreg <= (OTHERS => '0');
        ELSIF rising_edge(CLK) THEN
            sreg <= sreg(REG_LENGTH - 1 DOWNTO 0) & SYNC_IN;
        END IF;
    END PROCESS;
    EDGE <=
        '1' WHEN sreg = (REG_LENGTH - 1 DOWNTO 0 => '0') & '1' ELSE
        '0';
END BEHAVIORAL;
